[package]
name = "vert"
version = "0.1.0"
authors = ["Daniel Bergey <bergey@teallabs.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
